changes

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -43,6 +43,8 @@ Optional features:
   --disable-debugging             disable debugging (set NDEBUG) (default)
   --enable-raft-debugging         enable debugging of raft
   --disable-raft-debugging        disable debugging of raft (default)
+  --enable-raft-impl-debugging    enable debugging of raft implementation
+  --disable-raft-impl-debugging   disable debugging of raft implementation (default)
   --enable-threads                enable threads (EXPERIMENTAL)
   --disable-threads               disable threads (default)
   --enable-raft                   enable Raft clustering
@@ -64,6 +66,7 @@ DEPS=1
 FEATURE_DEBUG=0
 FEATURE_THREADS=0
 FEATURE_RAFT_DEBUG=0
+FEATURE_RAFT_IMPL_DEBUG=0
 FEATURE_RAFT=0
 FEATURE_OM=0
 SAVED_ARGS="$*"
@@ -103,6 +106,8 @@ while :; do
 		--disable-debugging) FEATURE_DEBUG=0 ;;
 		--enable-raft-debugging) FEATURE_RAFT_DEBUG=1 ;;
 		--disable-raft-debugging) FEATURE_RAFT_DEBUG=0 ;;
+		--enable-raft-impl-debugging) FEATURE_RAFT_IMPL_DEBUG=1 ;;
+		--disable-raft-impl-debugging) FEATURE_RAFT_IMPL_DEBUG=0 ;;
 		--enable-raft) FEATURE_RAFT=1 ;;
 		--disable-raft) FEATURE_RAFT=0 ;;
 		--enable-openmetrics) FEATURE_OM=1 ;;
@@ -126,6 +131,10 @@ SRCDIR=$(dirname "${0}")
 
 if [[ "${FEATURE_RAFT_DEBUG}" -eq 1 && "${FEATURE_RAFT}" -eq 0 ]]; then
 	{ echo "Cannot --enable-raft-debugging without --enable-raft" >&2; exit 1; }
+fi
+
+if [[ "${FEATURE_RAFT_IMPL_DEBUG}" -eq 1 && "${FEATURE_RAFT}" -eq 0 ]]; then
+	{ echo "Cannot --enable-raft-impl-debugging without --enable-raft" >&2; exit 1; }
 fi
 
 if [[ "$(realpath "${OBJDIR}")" = "$(realpath "${SRCDIR}")" ]]; then
@@ -428,7 +437,7 @@ if [[ "${LEX}" ]]; then
 	fi
 fi
 
-if [[ "${FEATURE_DEBUG}" -eq 1 || "${FEATURE_RAFT_DEBUG}" -eq 1 ]]; then
+if [[ "${FEATURE_DEBUG}" -eq 1 || "${FEATURE_RAFT_DEBUG}" -eq 1 || "${FEATURE_RAFT_IMPL_DEBUG}" ]]; then
 	echo "#undef NDEBUG" >> "${OBJDIR}"/config.h
 fi
 
@@ -450,6 +459,9 @@ fi
 	fi
 	if [[ "${FEATURE_RAFT_DEBUG}" -eq 1 ]]; then
 		echo "#define FEATURE_RAFT_DEBUG 1"
+	fi
+	if [[ "${FEATURE_RAFT_IMPL_DEBUG}" -eq 1 ]]; then
+		echo "#define FEATURE_RAFT_IMPL_DEBUG 1"
 	fi
 	if [[ "${FEATURE_RAFT}" -eq 1 ]]; then
 		echo "#define FEATURE_RAFT 1"
